### PR TITLE
t6-common: Updates for lollipop

### PR DESCRIPTION
**Pull request by Flyhalf205**
t6-common: Updates for lollipop

### CODE REVIEW

**Comment by intervigilium** [comment]
You may want to update the commit messages, it looks like you kept the version string from m7

**Comment by Flyhalf205** [comment]
I'm using that m7 version of libs. No success with mine, just black screen. Hex edit m7 libs does show t6 device.

**Comment by Flyhalf205** [comment]
Did camera testing. These libs are best suited for what we have right now. These commits are good to go.

**Comment by intervigilium** [comment]
Make sure you set the ro.cam.hw.version property in your device repo.

**Comment by Flyhalf205** [comment]
Thanks.
https://github.com/CyanogenMod/android_device_htc_t6-common/blob/cm-11.0/t6-common.mk#L159

**Pull request merged**
