### PR TITLE
pme: update blobs

### PR DESCRIPTION
**Pull request by Altaf-Mahdi**

### CODE REVIEW

**Comment by crpalmer** [comment]
Is thermal-engine working?  I just ran antutu and it hard reset with this in the console-ramoops:

[  918.275716] msm_thermal:msm_thermal_bite Tsens:11 reached temperature:115. System reset

**Comment by Altaf-Mahdi** [comment]
Did this happen with the stock blobs in this patch? I did run some tests and saw the big cores shutdown a number of times when temp reached about 60 which I never saw with the old op3 blobs, I can only assume stock thermal-engine has dependencies on thermal-monitor and pnp manager. I did test the new op3 nougat thermal blobs before this and saw very good throttling from both little and big cores.

**Comment by Altaf-Mahdi** [comment]
I just tested again with the blobs included in this patch, ran antutu with performance governor and noticed the big cores turn off a number of times between around 60-65, no actual frequency throttling but it made it through the test, I was monitoring msm_therm sensor through the test which only once got above 64, I did check sensor 11 straight after the test and it was around 60, probably dropped a little in that time.

**Comment by crpalmer** [comment]
I'm seeing these cpu temps

1482418465 783 799 838 861

and no throttling is occurring as all 4 cores are running at max freq.  Let me go back to the official kernel (I'm on a branch where I'm trying to bring up a clean version of the kernel on the caf branch but I haven't touched thermal yet).

**Comment by crpalmer** [comment]
Running antutu again with these patches and basically no changes with what
is committed in github.com/CyanogenMod and I am still seeing very high cpu
temps:

1482419785 848 864 912 938 43

(that is unix time, cpu0, cpu1, cpu2, cpu3, battery temps)

stracing thermal-engine looks to me like it is only reading battery temps
and because that temp isn't too high doesn't throttle.

**Comment by crpalmer** [comment]
What I was doing originally to test this is using some tiny tools I wrote

https://github.com/crpalmer/android_crp-tools

If you build those manually and install them then you can run

adb shell
inf-loop & inf-loop & inf-loop & inf-loop &

and then watch the cpu frequencies with

adb shell cpu-stats

and the temperatures with

adb shell monitor "/sys/class/thermal/thermal_zone[469]/temp"
/sys/class/thermal/thermal_zone11/temp
/sys/class/thermal/thermal_zone23/temp

It takes awhile for the temps to creep up.  If I leave the inf-loops
running and start antutu I get over 100 degrees pretty easily.

**Comment by Altaf-Mahdi** [comment]
This is a very good way of testing, I will test this out soon thanks. Did you not see the big cores turn off at all? I did see some very good and consistent throttling from the op3 nougat blobs using our stock thermal.conf, I could upload them to my git if you want to test them. I've been running in enforcing mode if that would make a difference.

**Pull request merged**
