### PR TITLE
m7-common: Add firmware blobs for 4.3 hardware keystore

### PR DESCRIPTION
**Pull request by blunden**
For more information about it and a sample app to verify it, check the link below.

http://nelenkov.blogspot.com/2013/08/credential-storage-enhancements-android-43.html

https://github.com/nelenkov/android-keystore

Precompiled APK: https://www.dropbox.com/s/qjnsixdth1p7x66/android-keystore-sample.apk

### CODE REVIEW

**Comment by intervigilium** [comment]
Does this actually work?

**Comment by hyperb1iss** [comment]
I was not able to make QSEECom load these on JF.

**Comment by blunden** [comment]
arcee was able to get it working on the Optimus G apparently so maybe someone should ask him how he did it.

**Comment by blunden** [comment]
It seems intervigil got it working properly.

**Comment by blunden** [comment]
He'll push the blobs when someone else verifies it. Closing this pull request.

**Pull request closed without merging**
