### PR TITLE
endeavoru/enrc2b: Revive HTC libril.so for in-call audio

### PR DESCRIPTION
**Pull request by thoemy**
The HTC libril.so listens on various sockets that are created by the HTC rild
service. libcall_volume.so uses these sockets to control the in-call audio and
other properties.

Change-Id: I9b2ab4afbc77114b29fcf3ede42e5de445259134

### CODE REVIEW

**Comment by thoemy** [comment]
Please don't merge yet.

**Comment by Lloir** [comment]
This is going to need to be merged, i will create a pull request for the enrc2b libril.so, as it's missing from this

**Comment by thoemy** [comment]
It's missing because it's already there.

**Comment by thoemy** [comment]
Good to go in from my side.

**Pull request merged**
